[package]
name = "stack"
version = "1.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opener = "0.6.1"
powershell_script = "1.1.0"
rand = "0.8"
reqwest = { version = "0.11.0", features = ["blocking"] }
