name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.54.0

      - name: Run tests
        run: cargo test

      - name: Merge pull request (if tests pass)
        if: ${{ success() }}
        uses: pascalgn/automerge-action@v0.14.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
